In [2]:
import numpy as np

### Dataset sintético ###

# Ejercicio 1 

# Nº de muestras
n = 200 

# Centroides
A = np.array([1, 0, 0, 0])
B = np.array([0, 1, 0, 0])

# Constante de separación
cte = 1

m = np.vstack((A,B))
m = m*cte # + cte

db = np.repeat(m, n/2, axis=0)

# Desviación estándar del ruido
dev = 1
db = db + np.random.normal(0, dev, db.shape)

tag = np.array(["A", "B"])
tags = np.repeat(tag, n/2)

In [52]:
# Ejercicio 6

db = np.array([[1,2,3],[4,5,6],[7,8,9]])
centr = np.array([[1,0,0],[0,1,1]])

centr = centr[:, np.newaxis]
resta = centr - db
norm = np.linalg.norm(resta, axis=2)
print(norm)

[[ 3.60555128  8.36660027 13.45362405]
 [ 2.44948974  7.54983444 12.72792206]]


In [53]:
# Ejercicio 7

centr_res = np.argmin(norm, axis=0)
print(centr_res)

[1 1 1]


In [75]:
# Ejercicio 8 (Implementación básica de K-means)

def k_means(X,n):

    # Selección random de centroides iniciales
    i = np.random.randint(0, db.shape[0]-1, n)
    centr = db[i]
    
    for i in range(10):
    
        # Distancia entre todos los puntos y los centroides (Ejericio 6)
        centr = centr[:, np.newaxis]
        resta = centr - db
        norm = np.linalg.norm(resta, axis=2)

        # Selección del centroide más cercano (Ejercicio 7)
        centr_res = np.argmin(norm, axis=0)

        # Recalculo de centroides
        lst = []
        for i in range(num_clust):
            lst.append(np.mean(db[centr_res==i], axis=0))
        centr = np.array(lst)
    
    return centr,centr_res

centr_r,tags_r = k_means(db, 2)
print(centr_r)

## Probar en R2/3 para verlo graficamente, spectation maximization ?

[[ 0.27780155  0.16648119 -0.11597141  0.63674012]
 [ 0.65863166  0.83544361  0.11778707 -0.88145984]]


In [5]:
# Ejercicio 2 (PCA)

X = np.array([[0.8,0.7],[0.1,-0.1], [0.1,5]])

# Estandarización de datos
mean = X.mean(axis=0)
std = X.std(axis=0)
sX = (X-mean)/std

# Matriz de covarianza
M = np.cov(sX.T)
print(M.shape)

# Cálculo de autovalores y autovectores
eig_vals, eig_vecs = np.linalg.eig(M)
max_ev_idx = np.argmax(eig_vals)

# Proyección sobre la dirección de la componente principal
print(sX)
P = eig_vecs[max_ev_idx,:]
sX.dot(P)

(2, 2)
[[ 1.41421356 -0.52093947]
 [-0.70710678 -0.87815511]
 [-0.70710678  1.39909459]]


array([-0.63164017,  1.12094944, -0.48930927])

In [80]:
print(centered_X)

[[ 0.35  0.4 ]
 [-0.35 -0.4 ]]
